export const SET_USER = 'SET_USER' 

export const SET_CHANNEL = 'SET_CHANNEL' 

export const SET_FAVORITECHANNEL = 'SET_FAVORITECHANNEL' 

export const REMOVE_FAVORITECHANNEL = 'REMOVE_FAVORITECHANNEL' 
